obj-$(CONFIG_CRYPTO_DEV_CPT) += cptpf.o cptvf.o
cptpf-objs := cptpf_main.o cptpf_mbox.o cptpf_domain.o
cptvf-objs := cptvf_main.o cptvf_reqmanager.o cptvf_mbox.o cptvf_algs.o
ccflags-y := -I$(src)/../../../net/ethernet/cavium/octeontx-83xx/
